apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: votelabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votelabel
  template:
    metadata:
      labels:
        app: votelabel
    spec:
      containers:
      - name: vote
        image: thjulian23/brief-8-tj-2:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi"
        env:
        - name: REDIS
          value: "rediscluster"
        - name: STRESS_SECS
          value: "2"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redispw
              key: password